POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "user_id": 1,
    "firstname":"Kostas",
    "lastname":"Theofilis",
    "email":"kt@gmail.com",
    "password":"1234",
    "mobile": 6948604407
}

###
GET http://localhost:3000/users/5
###
GET http://localhost:3000/users
###
POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "kt@gmail.com",
    "password": "1234"
}

###

PATCH  http://localhost:3000/users/5
Content-Type: application/json

{
    "address": "Περραιβού 24",
    "city": "Χαϊδάρι",
    "city_id": 12461,
    "_id_city": "Αττική"
}
###