POST  http://localhost:3000/applications/api/submit
Content-Type: application/json

{
        "application_id": 1019,
        "user_id": 1,
        "status": "Αποθηκευμένη",
        "application_type": "Αναγνώρισης",
        "application_date": "{{$datetime 'YYYY-MM-DD'}}",
        "type_of_studies": "Δια ζώσης",
        "country_of_studies": "Ελλάδα",
        "university": "ΕΚΠΑ",
        "university_type": "Πανεπιστήμιο",
        "title_of_studies": "Επιστήμη Υπολογιστών",
        "credits": 250,
        "sign_in_date": "{{$datetime 'YYYY-MM-DD'}}",
        "date_of_graduation": "{{$datetime 'YYYY-MM-DD'}}",
        "years_of_studies": 4,
        "university_department_of_choice": "Κάποιο"
}
###
GET http://localhost:3000/applications/api
###
GET http://localhost:3000/applications/api/121
###
PATCH  http://localhost:3000/applications/api/update/123
Content-Type: application/json

{
    "temp": "makaronia me kima"
}






###
POST  http://localhost:3000/users/register
Content-Type: application/json

{
    "user_id": 1,
    "firstname":"Kostas",
    "lastname":"Theofilis",
    "email":"kt@gmail.com",
    "password":"1234",
    "mobile": 6948604407
}
###
GET http://localhost:3000/users/5
###
GET http://localhost:3000/users
###
POST  http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "kt@gmail.com",
    "password": "1234"
}

###

PATCH  http://localhost:3000/users/5
Content-Type: application/json

{
    "address": "Περραιβού 24",
    "city": "Χαϊδάρι",
    "city_id": 12461,
    "_id_city": "Αττική"
}
###